# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - "*"


pool: AWS-D60

resources:
  repositories:
  - repository: shared-library
    name: jenkins
    type: git

variables:
  COMPONENT: cart

stages:
- template: test.yml@shared-library
